package com.lanmessager.concurrent;

/**
 * Report is information generated by {@link Task}, and collected by {@link TaskExecutor}. 
 *
 * @param <K> The key type used to retrieve {@link Task}.
 */
public class Report<K> {
	private K key;

	public Report(K key) {
		this.key = key;
	}
	
	public K getKey() {
		return key;
	}
}
